services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: cust.io-api
    container_name: cust.io-api-live
    ports:
      - "8080:8080"
  webapp:
    depends_on:
      - api
    build:
      context: ./webapp
      dockerfile: Dockerfile
    image: cust.io-webapp
    container_name: cust.io-webapp-live
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    volumes:
      - ./webapp:/webapp
